Display model training warning message only when real modifications w…
vertigo-io/vertigo-bot-factory pull request #102
Opened 2021-11-05 10:30 UTC by cedricMarechal

…ere detected

2021-11-08 15:13 UTC, skerdudou requested changes
Eviter de trop éparpiller les éléments permettant de comparer si une modification a eu lieu. Soit le détecter en amont et passer un booleen, soit le vérifier au plus près de la où l'on en a besoin.
Si l'on a plus besoin de passer de paramètre (ou alors un booleen), on est pas obligé non plus de passer par un hash, une vérification de ce type est envisageable
```
public static boolean isNluTrainingSentenceEquals(DtList<NluTrainingSentence> sentences1, DtList<NluTrainingSentence> sentences2) {
    Assertion.check()
        .isNotNull(sentences1)
        .isNotNull(sentences2);

    if (sentences1.size() != sentences2.size()) return false;

    for (int i = 0; i < sentences1.size(); i++) {
        if (!sentences1.get(i).getText().equals(sentences2.get(i).getText())) return false;
    }
    return true;
}
```

2021-11-08 15:13 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/utils/HashUtils.java
> +	public HashUtils() {
=> private

2021-11-09 16:23 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/AbstractTopicController.java
> +		topicServices.save(topic, chatbot, service.isEnabled(object, topic.getIsEnabled(), chatbot), nluTrainingSentences, nluTrainingSentencesHash, nluTrainingSentencesToDelete);
Les nluTrainingSentences sont potentiellement mise à jour dans le controller par l'appel  d'autres services. Du coup le hash est calculé a l'init du context lors du chargement de la page. Il est stocké dans le context et réutiliser au moment de la sauvegarde pour comparer avec un nouveau hash des nluTrainingSentences .

2021-11-10 07:33 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/AbstractTopicController.java
> +		topicServices.save(topic, chatbot, service.isEnabled(object, topic.getIsEnabled(), chatbot), nluTrainingSentences, nluTrainingSentencesHash, nluTrainingSentencesToDelete);
Le contrôleur ne sauvegarde en bdd qu'une fois (ou le devrais, tout doit être mis dans le même appel de service pour gérer la transaction bdd) . Dès lors on peux calculer l'état avant / après à ce moment en récupérant l'ancienne liste depuis la bdd. Le faire de préférence au plus proche possible de la ou c'est utile.

2021-11-10 09:36 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/AbstractTopicController.java
> +		topicServices.save(topic, chatbot, service.isEnabled(object, topic.getIsEnabled(), chatbot), nluTrainingSentences, nluTrainingSentencesHash, nluTrainingSentencesToDelete);
Effectivement, les nluTrainingSentences  n'étaient bien sauvegardées qu'une seule fois en bdd. J'ai modifié le code pour récupérer l'ancienne liste depuis la bdd et déplacé le calcul du hash avant/après dans le service.

2021-11-15 13:22 UTC, merged