CHATBOT-299 - simplify changes between scripted and simple topics
vertigo-io/vertigo-bot-factory pull request #109
Opened 2021-11-15 13:17 UTC by cedricMarechal

2021-11-18 11:03 UTC, skerdudou requested changes

2021-11-18 11:03 UTC, skerdudou commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/topicsList.html
>  			}
A simplifier, plus besoin de fonction js pour ca (se baser sur l'historique du fichier, ou sur d'autres exemples).

2021-11-18 11:03 UTC, skerdudou commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/topicsList.html
>  			}
J'ai ressortit ca de l'historique :
`<a th::href="|'@{/bot/{id}/smallTalk/(id=${model.bot.botId})}'+props.row.smtId|"`

2021-11-19 16:40 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/ScriptIntentionServices.java
> +		return isEnabled(scriptIntention, topic.getIsEnabled(), chatbot);
L'appelant ne connait pas le type de topic (smalltalk ou scriptIntention). Or le isEnabled dépend du type de topic. Du coup faut nécessairement le faire dans l'implémentation du saveTopic spécifique à chaque type.

2021-11-19 16:40 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/SmallTalkServices.java
> +		return isEnabled(smallTalk, topic.getIsEnabled(), chatbot);
Même réponse

2021-11-19 16:40 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
> +				save(topic, chatbot, isEnabled, nluTrainingSentences, nluTrainingSentencesToDelete);
Même réponse

2021-11-19 16:42 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/smallTalkDetail.html
> +			<vu:button-link th:if="${model.modeEdit}" url="@{/bot/{id}/smallTalk/(id=${model.bot.botId})} + ${model.smallTalk.smtId}" th:ariaLabel="#{action.cancel}" icon="fas fa-ban"
Si, le fragment "content-header-actions" est inclus conditionnellement en fonction du type de topic dans TopicDetail.html

2021-11-19 16:42 UTC, cedricMarechal commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/scriptIntentionDetail.html
> +			<vu:button-link th:if="${model.modeEdit}" url="@{/bot/{id}/scriptIntention/(id=${model.bot.botId})} + ${model.scriptIntention.sinId}" th:ariaLabel="#{action.cancel}" icon="fas fa-ban"
Si, le fragment "content-header-actions" est inclus conditionnellement en fonction du type de topic dans TopicDetail.html

2021-11-22 10:38 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/TopicDetailController.java
> +                    dtObjectErrors.addError(dtField.getName(), MessageText.of("Le champ doit être renseigné")); // TODO: use same i18n resource when avaiable in DefaultDtObjectValidator
Copié collé de BotDetailControlleur, a modifier pour correspondre a la classe `Topic` et l'ancien code de vérification (pas de isHtmlEmpty !). (J'ai déjà pensé à simplifier / capitaliser un peu ces vérifs dans un second temps)

2021-11-22 10:38 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/ScriptIntentionServices.java
> +		return isEnabled(scriptIntention, topic.getIsEnabled(), chatbot);
Si il est capable d'appeler le saveTopic spécifique au type, alors il peux faire de même avec le siEnabled.

2021-11-22 10:38 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/SmallTalkServices.java
> +		return isEnabled(smallTalk, topic.getIsEnabled(), chatbot);
idem

2021-11-22 10:49 UTC, skerdudou requested changes

2021-11-22 10:49 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicInterfaceServices.java
> +	 * @return
A compléter.
Au passage, renommer l'interface en `ITopicService` par convention.

2021-11-22 10:49 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
> +	protected TopicLabelServices topicLabelServices;
Toujours à traiter.

2021-11-22 10:49 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
> +	 * @param initialLabels
A compléter

2021-11-22 10:49 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/ScriptIntentionServices.java
> +		return isEnabled(scriptIntention, topic.getIsEnabled(), chatbot);
J'avais même mis la solution ici https://github.com/vertigo-io/vertigo-bot-factory/pull/109#discussion_r752120300

2021-11-22 15:54 UTC, skerdudou approved these changes
Ok après ces derniers commentaires

2021-11-22 15:54 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/TopicDetailController.java
Un peu dommage de pas avoir trouvé un nom plus parlant que dtObject pour la variable.
Sinon dans la lignée d'avoir un objet avec les spécificités du topic passé en paramètre, il serait bien de créer un DtObject (dans un ksp) qui va contenir le small talk, la liste des utterText et la liste des bouttons.
Cela sera plus cohérent (par de paramètres spécifique a un type de topic dans la signature) et simplifiera la signature de la méthode ce qui rendra le tout plus lisible.

2021-11-22 15:54 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/TopicDetailController.java
>      private void saveTopic(final Topic topic,
cette méthode a-t-elle encore un intéret ?

2021-11-22 15:54 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
>  	protected NluTrainingSentenceServices nluTrainingSentenceServices;
=> private aussi

2021-11-23 12:40 UTC, merged