Add conf for docker build on Jenkins
vertigo-io/vertigo-bot-factory pull request #112
Opened 2021-11-19 15:54 UTC by cedricMarechal

2021-11-30 13:19 UTC, skerdudou requested changes

2021-11-30 13:19 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-confluence
> +ARG VERSION
ligne dupliquée

2021-11-30 13:19 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-confluence
> +COPY Runner/plugins/vertigo-bot-confluence-$VERSION.jar /opt/plugins/vertigo-bot-confluence-$VERSION.jar
Pourquoi pas de `--chown=tomcat` ?

2021-11-30 13:19 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-confluence
> +ENV CONFLUENCE_URL https://preprod-jira-temp.kleegroup.com/confluence
Eviter de mettre dans l'image docker (qui va être publique) des URL "a nous"

2021-11-30 13:19 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ARG VERSION
ligne dupliquée

2021-11-30 13:19 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +COPY Runner/plugins/ /opt/plugins/
Pourquoi enlever le `--chown=tomcat` ?

2021-11-30 13:19 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ENV WEB_SERVICE http://comu-prod-batch:8001/sigRest/v2/tools/health-check
Même remarque pour les valeurs par défaut dans l'image docker

2021-11-30 13:22 UTC, cedricMarechal commented on vertigo-bot-docker/build/DockerfileRunner-confluence
> +ARG VERSION
C'est nécessaire car le ARG VERSION déclaré avant le FROM ne peut pas être utilisé pour les commandes après le FROM. On est obligé de le déclarer une deuxième fois après le FROM pour qu'il soit utilisable dans les instructions en dessous.

2021-11-30 13:23 UTC, cedricMarechal commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ARG VERSION
C'est nécessaire car le ARG VERSION déclaré avant le FROM ne peut pas être utilisé pour les commandes après le FROM. On est obligé de le déclarer une deuxième fois après le FROM pour qu'il soit utilisable dans les instructions en dessous.

2021-11-30 15:00 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-confluence
> +ARG VERSION
ok !

2021-11-30 15:00 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ARG VERSION
ok !

2021-12-01 10:34 UTC, skerdudou approved these changes

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileDesigner
> -ENV INFLUXDB_URL http://analytica.part.klee.lan.net:8086
On peux laisser mais avec une valeur exemple

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner
on peux laisser

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-confluence
> +ENV CONFLUENCE_URL https://confluence.com
par sécurité, peut être mettre une fausse url plutot que d'essayer de se connecter à leurs serveurs

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ENV CONFLUENCE_URL https://confluence.com
idem

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ENV JIRA_URL https://jira.com
idem

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ENV SIG_URL http://sig.com
idem

2021-12-01 10:34 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileRunner-plugin
> +ENV WEB_SERVICE http://sig-webservice.com
idem

2021-12-01 10:35 UTC, skerdudou commented on vertigo-bot-docker/build/DockerfileDesigner
> -ENV INFLUXDB_URL http://analytica.part.klee.lan.net:8086
par exemple le nom du conteneur que l'on utilise dans notre stack compose

2021-12-01 13:01 UTC, skerdudou commented on vertigo-bot-docker/docker-compose.yml.sample
> +        target: /opt/keycloak/keycloak.json
peut être simplifié en
```suggestion
      - ./keycloak.json:/opt/keycloak/keycloak.json:ro
```
et au passage le fichier est passé en lecture seule depuis le conteneur

2021-12-01 13:22 UTC, merged