Features/smt to bt
vertigo-io/vertigo-bot-factory pull request #17
Opened 2021-05-04 13:50 UTC by valerian-baillet

2021-05-05 08:13 UTC, vprima commented on vertigo-bot-designer/src/main/resources/sql/v_1_0/alter_21_04_30-2.sql
> +
Si le code va être utilisé pour identifier le topic, ça vaut pas le coup de rajouter une contrainte d'unicité pour avoir une sécurité supplémentaire  dans la base de donnée ?

2021-05-07 15:23 UTC, skerdudou requested changes

2021-05-07 15:23 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/BtBuilderUtils.java
> +		addSpaceQuote(bt);
pourquoi un espace en plus ?

2021-05-07 15:23 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/SmallTalkExportServices.java
> +	}
?

2021-05-07 15:23 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/TopicsExportUtils.java
> +			final List<String> topicNlu = nlus.stream().filter(x -> x.getTopId().equals(topId)).map(x -> x.getText()).collect(Collectors.toList());
```suggestion
			final List<String> topicNlu = nlus.stream()
				.filter(x -> x.getTopId().equals(topId))
				.map(NluTrainingExport::getText)
				.collect(Collectors.toList());
```

2021-05-07 15:23 UTC, skerdudou commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/TopicsExportUtils.java
> +			final List<String> topicNlu = nlus.stream().filter(x -> x.getTopId().equals(topId)).map(x -> x.getText()).collect(Collectors.toList());
Séparer les opérations des stream sur des lignes dédiées augmente la lisibilité

2021-05-10 09:55 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/TrainingServices.java
> +	private BotExport exportBot(@SecuredOperation("botContributor") final Chatbot bot) {
Pour moi c'est plus clair de sortir un service spécialement pour l'export qui est utilisé pour l'entrainement

2021-05-10 10:01 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/SmallTalkExportServices.java
> +	}
Va permettre de rajouter les utters text crée par Victor

2021-05-10 13:31 UTC, merged