Security improvements
vertigo-io/vertigo-bot-factory pull request #198
Opened 2022-10-06 12:46 UTC by cedricMarechal

2022-10-06 16:22 UTC, skerdudou requested changes
Chiffrement à revoir (salt / IV).
Le reste ok

2022-10-12 17:37 UTC, skerdudou approved these changes

2022-10-12 17:37 UTC, skerdudou commented on vertigo-bot-commons/src/main/java/io/vertigo/chatbot/commons/PasswordEncryptionServices.java
> +    private void initEncryptionParam() {
Quel intérêt de retenter une initialisation qui n'aurais pas marché au boot pour chaque encrypt/decrypt ?

2022-10-13 07:24 UTC, cedricMarechal commented on vertigo-bot-commons/src/main/java/io/vertigo/chatbot/commons/PasswordEncryptionServices.java
> +    private void initEncryptionParam() {
Pour une raison que je ne maitrise pas, le start n'est pas appelé quand la classe est injectée dans le custom change de liquibase. Du coup l'encryption password, le secretKeyFactory et le cipher n'étais pas initialisé lors de la migration et ça plantait. C'est pour ça que j'ai rajouté cette initialisation pour chaque encrypt/decrypt et laissé le start() pour les boot après la migration. Preneur d'une explication/solution sur le start() dans le custom change si tu en as :)

2022-10-13 08:07 UTC, skerdudou commented on vertigo-bot-commons/src/main/java/io/vertigo/chatbot/commons/PasswordEncryptionServices.java
> +    private void initEncryptionParam() {
La migration Liquibase est faite très tôt dans le boot pour que les composants aient la BDD à jour au démarrage (par ex Orchestra pour les batch en a besoin), on est pas totalement démarré donc, on est "en cours de boot"
Le mieux c'est de laisser cette classe "propre" et d'appeler manuellement le `start()`, une fois, au début dans la classe de migration Liquibase (et si le start est fait une seconde fois par le boot c'est pas grave et pas besoin d'avoir les if xx == null)

2022-10-13 12:09 UTC, cedricMarechal commented on vertigo-bot-commons/src/main/java/io/vertigo/chatbot/commons/PasswordEncryptionServices.java
> +    private void initEncryptionParam() {
C'est corrigé

2022-10-13 12:42 UTC, merged