export
vertigo-io/vertigo-bot-factory pull request #29
Opened 2021-06-10 11:48 UTC by vprima

2021-06-15 08:19 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
> +		final Export export = new ExportBuilder(ExportFormat.CSV, "test")
Nom à ne pas oublié de changer

2021-06-15 08:19 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/ScriptIntentionExportServices.java
> +		exportBuilder.beginSheet(scriptIntention, "scriptIntenttion");
erreur de typo

2021-06-15 08:19 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/controllers/bot/TopicsListController.java
> +		return topicServices.exportTopic(listTopics);
renommer ou changer l'autre fonction pour ne pas confondre les fonctions d'exports pour le bot et pour le fichier

2021-06-16 08:39 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/ScriptIntentionExportServices.java
> +		exportBuilder.beginSheet(scriptIntention, "scriptIntenttion");
Je n'utiliserais pas cette méthode au final de toute façon

2021-06-25 07:47 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/topicsList.html
> +					<vu:include-data-primitive key="locale" />
pas forcément besoin de la locale. ça me permettait de changer les libellés à la volée mais tu utilises le process vertigo.

2021-06-25 07:49 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/topicsList.html
> +					<vu:include-data-primitive key="locale" />
d'ailleurs à voir si on ne crée pas un composent vertigo pour créer des popins à sélection plus rapidement.

2021-06-25 08:13 UTC, valerian-baillet requested changes

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
> +				throw new VUserException("The responses cannot contain the following characters : '[', ']', '|', '¤'. ");
à supprimer mais faire une fonction au lieu de copier coller le bout de code plusieurs fois

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/file/TopicFileExportServices.java
> +	public void importTopicFromList(final Chatbot chatbot, final List<TopicFileExport> list) throws IOException {
couper la fonction en plusieurs sous fonctions pour une meilleure lecture 

- check de code
- Ajout des topics
- Ajout des nlutrainings

On peut même aller plus loin en rajoutant des sous fonctions: check de catégories etc...

Le but c'est qu'on puisse lire rapidement le travail de cette fonction juste à partir des noms des sous fonctions.

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/file/TopicFileExportServices.java
> +	public void gestionScriptIntention(final Chatbot chatbot, final Topic topic, final TopicFileExport tfe, final boolean creation, final DtList<NluTrainingSentence> nluTrainingSentences) {
passer en privée si on ne doit pas l'atteindre de l'extérieur

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/export/file/TopicFileExportServices.java
> +		SmallTalk smt = new SmallTalk();
passer en privée si on ne doit pas l'atteindre de l'extérieur

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/quarto/plugins/exporter/csv/CSVExporter.java
> + * @author pchretien, npiedeloup
copier coller !

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/java/io/vertigo/quarto/plugins/exporter/csv/CSVExporter.java
> + * @author pchretien, npiedeloup
obligé de le récupérer dans notre code ?

2021-06-25 08:13 UTC, valerian-baillet commented on vertigo-bot-designer/src/main/javagen/io/vertigo/chatbot/commons/domain/topic/DtResources.java
> +	fldSelectCategory$topCatId,
j'ai pas vu les traductions mais je peux me tromper

2021-06-25 08:16 UTC, vprima commented on vertigo-bot-designer/src/main/webapp/WEB-INF/views/builder/bot/topicsList.html
> +					console.log(params);
Je supprime toute la fonction, au final j'ai utilisé v-close-popup

2021-06-25 08:32 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/NluTrainingSentenceServices.java
> +		final String[] listTrainingPhrases = tfe.getTrainingPhrases().split("\\|");
https://stackoverflow.com/questions/10796160/splitting-a-java-string-by-the-pipe-symbol-using-split
split uses regular expression and in regex | is a metacharacter representing the OR operator.

2021-06-25 08:35 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/quarto/plugins/exporter/csv/CSVExporter.java
> + * @author pchretien, npiedeloup
C'est ce qu'on a fait avec steven, obligés de surcharger, par défaut ça export en UTF8, et nous on le veut en cp1252 en sortie et en entrée pour pouvoir modifier les fichiers via excel sans problèmes d'encodage

2021-06-25 12:36 UTC, vprima commented on vertigo-bot-designer/src/main/javagen/io/vertigo/chatbot/commons/domain/topic/DtResources.java
> +	fldSelectCategory$topCatId,
Je supprime, je n'utilise pas cet objet au final

2021-06-29 09:54 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/ScriptIntentionServices.java
> +		isEnabled &= scriptIntention.getScript() != null ? !scriptIntention.getScript().isBlank() : false;
Même si il est incomplet ?

2021-06-29 11:19 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicCategoryServices.java
> +		final DtList<TopicCategory> listCategories = topicCategoryDAO.getCategoryByCodeBotId(botId, code);
Si. Mais au final, pas besoin de cette méthode pour l'instant, j'utilise une map pour récupérer toutes les catégories d'un coup

2021-06-29 11:20 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/TopicServices.java
> +				throw new VUserException("The responses cannot contain the following characters : '[', ']', '|', '¤'. ");
Oui je supprimerai quand on mergera ce que tu as fait

2021-06-29 11:56 UTC, vprima commented on vertigo-bot-designer/src/main/java/io/vertigo/chatbot/designer/builder/services/topic/ScriptIntentionServices.java
> +		isEnabled &= scriptIntention.getScript() != null ? !scriptIntention.getScript().isBlank() : false;
Avec mes changements :
Script complet -> le script sera activé selon ce qui a été choisi pour le topic (création normale ou bien import, possibilité de réactiver/désactiver)
Script incomplet : désactivé quoi qu'il arrive, création normale ou import

2021-07-07 12:11 UTC, merged